### ISSUE TITLE
Add Netlify CMS

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-styleguide#2]
Allow editors to work in the context of a CMS. The field requirements will need to be addressed as we go, though the basic fieldset should include:

- title/component name
- description (not sure if this is body or front matter)
- repeatable field for code (I "think" repeatable, to show variations)

Note: Code field should allow editors to drop in code, but see the code as code as well as rendered (will require previews to be built to show code output).

**Comment by regisphilibert** [comment]
The only hurdle for now on this is the path of the directories which might differ from project to project. 
`folder: content/en/styleguide/atoms`

We can direct our users on which directory to use, `styleguide`. But the language will be problematic as our netlify config file will have the collection point to `en/styleguide/atoms` on `thenewdynamic.com` or `styleguide/atoms` on `ndbooks.com` for example.

There is no easy way to dynamically set this using a setting. Not with a hardcoded config file anyway.

**Comment by regisphilibert** [comment]
Second hurdle is the `branch`, `local` etc... 🤔

A bit problematic... as people will need to update those on a frequent basics...

**Comment by budparr** [comment]
Once we have a language declared in Hugo, does everything have to be in a language folder? At any rate, I think that's probably fine. 

Not sure I understand the last one. We typically use `branch: master` and I imagine others do, too. No?

**Comment by regisphilibert** [comment]
Well yes but what if, we want to switch to local. Or we need to update the branch. We won't have any control over this config in the stylesheet (it can't inherit the project's), so user will have to create its own Styleguide netflycms config and drop it in `static/styleguide/cms`

**Comment by budparr** [comment]
I use thenewdynamic.org on local without changing the branch.

**Comment by regisphilibert** [comment]
yes but you add `local_backend: true`, so only adding/removing this would be a problem? Or I am missing something maybe.

**Comment by budparr** [comment]
I've never changed it on thenewdynamic.org and have edited both on the server and locally

**Comment by regisphilibert** [comment]
What was the value you never changed though, true or false, as in `local_backend: true`?

**Comment by budparr** [comment]
always true

**Comment by regisphilibert** [comment]
I see! This is great then! Thanks for bearing with me.
